# Name of site (displayed in the header)
name: Sergey Gospodarets

# Short bio or description (displayed in the header)
description: JavaScript/HTML/CSS blog

# URL of your avatar or profile pic
avatar: /images/avatar.png

#
# Flags below are optional
#

# Includes an icon in the footer for each username
footer-links:
  dribbble:
  email: sgospodarets@gmail.com
  facebook:
  flickr:
  github: malyw
  instagram:
  linkedin: gospodarets
  pinterest:
  rss: malyw.github.io # make sure the "url" above is set!
  twitter: malyw

# This will enable commenting on posts
disqus: malyw-github-io

# Google Analytics web tracking code
google_analytics: UA-53471595-1

# Website URL
# Used for Sitemap.xml and your RSS feed
url: http://malyw.github.io

# If hosting site at a Project repository on GitHub pages
# (http://username.github.io/repository-name)
# and NOT your User repository (http://username.github.io)
# then add in the baseurl here, like this: "/repository-name"
baseurl: ""

#
#
#

markdown: redcarpet
highlighter: pygments
permalink: /:title

# plug-ins
gems:
  - jemoji # Emoji please!
  - jekyll-sitemap # Create a sitemap using the official Jekyll sitemap gem

# Exclude these files from production _site
exclude:
    - Gemfile
    - Gemfile.lock
    - LICENSE
    - README.md
    - Gruntfile.js
    - package.json
    - node_modules