author: Sergey Gospodarets
keywords: javascript,js,html,html5,css,css3,git,shell,node.js,frontend
personal-site-url: http://gospodarets.com
google-plus-account-url: https://plus.google.com/u/0/+SergeyGospodarets
google-plus-posts: https://plus.google.com/u/0/+SergeyGospodarets/posts
# Name of site (displayed in the header)
name: Sergey Gospodarets Blog

# Short bio or description (displayed in the header)
description: A front end web development blog

# URL of your avatar or profile pic
avatar: /images/avatar.jpg

#
# Flags below are optional
#

# Includes an icon in the footer for each username
footer-links:
  dribbble:
#  email: sgospodarets@gmail.com
  facebook: sergeygospodaretsblog
  flickr:
  github: malyw
  instagram:
  linkedin: gospodarets
  pinterest:
  rss: blog.gospodarets.com # make sure the "url" above is set!
  twitter: malyw
  googleplus: SergeyGospodarets

# http://jekyllrb.com/docs/pagination/
paginate: 5

# This will enable commenting on posts
disqus: malyw-github-io

# Google Analytics web tracking code
google_analytics: UA-53471595-1

# Google custom search ID
google_search: 012363491708652379866:741arfehybe

# Share buttons ID
share_buttons: d17f6eee-8573-4fba-b16e-2bca31a25157

# Website URL
# Used for Sitemap.xml and your RSS feed
url: http://blog.gospodarets.com

# If hosting site at a Project repository on GitHub pages
# (http://username.github.io/repository-name)
# and NOT your User repository (http://username.github.io)
# then add in the baseurl here, like this: "/repository-name"
baseurl: ""

#
#
#

markdown: redcarpet
highlighter: pygments
permalink: /:title

# Exclude these files from production _site
exclude:
    - Gemfile
    - Gemfile.lock
    - LICENSE
    - README.md
    - Gruntfile.js
    - package.json
    - node_modules
    - other

# Gems
gems:
  - jemoji # Emoji please!
  - jekyll-sitemap

# Tagging
tag_page_layout: tag_page
tag_page_dir: tag