author: Serg Gospodarets
keywords: javascript,js,html,html5,css,css3,git,shell,node.js,frontend
personal-site-url: https://gospodarets.com
google-plus-account-url: https://plus.google.com/u/0/+SergeyGospodarets
google-plus-posts: https://plus.google.com/u/0/+SergeyGospodarets/posts
# Name of site (displayed in the header)
name: Serg Gospodarets Blog

# Short bio or description (displayed in the header)
description: A front end web development blog with tutorials and ideas about JavaScript, AngularJS, jQuery, CSS, CSS3 and HTML, HTML5
description_short: A front end web development blog

# URL of your avatar or profile pic
avatar: /images/avatar.jpg
avatar2x: /images/avatar2x.jpg
avatar3x: /images/avatar3x.jpg

#
# Flags below are optional
#

# Web masters verification
web-master-verifications:
  google: 7cCa3PUlThC4fbmii_QaCaQclo2nB5_d4b4vbhZrL4I
  bing: 464A77B6880D4837BA420DEDB2D9CFF7
  yandex: 66d8056d3b1e88fd

# Includes an icon in the footer for each username
footer-links:
  dribbble:
#  email: sgospodarets@gmail.com
  facebook: sergeygospodaretsblog
  flickr:
  github: malyw
  instagram:
  linkedin: gospodarets
  pinterest:
  rss: blog.gospodarets.com # make sure the "url" above is set!
  feedburner: https://feeds.feedburner.com/sergey_gospodarets_blog # RSS alternative subscription
  twitter: malyw
  googleplus: SergeyGospodarets

# https://jekyllrb.com/docs/pagination/
paginate: 5

# This will enable commenting on posts
disqus: malyw-github-io

# Google Analytics web tracking code
google_analytics: UA-53471595-1

# Google custom search ID
google_search: 012363491708652379866:741arfehybe

# Share buttons ID
share_buttons: d17f6eee-8573-4fba-b16e-2bca31a25157

# Website URL
# Used for Sitemap.xml and your RSS feed
url: https://blog.gospodarets.com
demos_code_base_url: https://github.com/malyw/malyw.github.io/tree/master/demos

# If hosting site at a Project repository on GitHub pages
# (https://username.github.io/repository-name)
# and NOT your User repository (https://username.github.io)
# then add in the baseurl here, like this: "/repository-name"
baseurl: ""

#
#
#

markdown: redcarpet
redcarpet:
    extensions: [with_toc_data]

highlighter: rouge
permalink: /:title

# Exclude these files from production _site
exclude:
    - Gemfile
    - Gemfile.lock
    - LICENSE
    - README.md
    - Gruntfile.js
    - package.json
    - node_modules
    - other

# Gems
gems:
  - jekyll
  - jemoji
  - jekyll-sitemap
  - jekyll-paginate
  - redcarpet
  - jekyll-gist
  - jekyll-feed
  - pygments.rb

# Tagging
tag_page_layout: tag_page
tag_page_dir: tag